var dico1=["CITE","TUER","JURON","VENIR","CULOT","RUCHE","PETER","ECART",
"MUGIT","","AGITE","FIGER","VOUER","DELIA","DECUS","QUART","THUNE","BRELE",
"CADET","LITRE","STICK","NOTRE","PUANT","TENEZ","TENIR","HONTE","FANER",
"FONTE","GEMIS","USER","ATLAS","TOURS","NOYAU","BRAVE","CITER","COMTE",
"HATE","HATER","EXACT","TATOU","PAVOT","COGNE","PARER","FUSEE","PEONS",
"SBIRE","FOIRE","INPUT","OUAIS","SEVIR","GARDE","TIENS","LUTTE",
"MEURT","RETRO","VITE","SOEUR"];

var nbrMots = dico1.length;

var dico2=["COUTER","HYMNES","SACRER","CHERIR","MESSES","ASPIRE","MOELLE",
"INFAME","DECHUT","YAOURT","CALCUL","ENFLER","GARNIT","MENTIR","DIESEL",
"GANACHE","CALEPIN","PARLOIR","CALINER","ACHEVER","INVITER","VIVANTE",
"OBJECTE","ABJECTE","BELIERS","ENDORMI","DESSERT","ELARGIR","PARFOIS",
"VOYAGER","HARICOT","DIPLOME","GAGNANT","SEGMENT","GLISSADE","NIRVANAS",
"VIVIFIER","ENVISAGE","SYNERGIE","MEPRISE","ACCEPTER","HORMONES","DERISION",
"MENSUEL","MIELLEUX","BUCHETTE","PRINCIPE","SEIGNEUR","MASCOTTE","TRICHEUR",
"TREMPLIN","VIGILANT","COMPTE","GARDER","SAOULE"];

var nbrMots = dico2.length;